"""
conftest.py — Shared pytest fixtures and configuration.

Integration tests (those marked with @pytest.mark.integration) require the
model artifacts in data/outputs/ and data/processed/, which are generated by
running the notebooks and are gitignored. In CI these tests are skipped
automatically. Run them locally after executing notebooks 01–06.
"""

import pathlib

import pytest
from fastapi.testclient import TestClient

_OUTPUTS_DIR = pathlib.Path(__file__).resolve().parents[1] / "data" / "outputs"
_artifacts_present = _OUTPUTS_DIR.exists() and any(_OUTPUTS_DIR.iterdir())


def pytest_configure(config):
    config.addinivalue_line(
        "markers",
        "integration: requires model artifacts from notebooks (data/outputs/). Skipped in CI.",
    )


def pytest_collection_modifyitems(config, items):
    if _artifacts_present:
        return
    skip = pytest.mark.skip(
        reason="data/outputs/ not found — run notebooks 01–06 first, "
        "or use `pytest -m 'not integration'` to run only CI-safe tests."
    )
    for item in items:
        if "integration" in item.keywords:
            item.add_marker(skip)


@pytest.fixture(scope="session")
def client():
    """Session-scoped TestClient — loads DataStore once for the full test run."""
    from src.api.main import app

    with TestClient(app) as c:
        yield c
