"""
loader.py — DataStore: loads all pre-computed artefacts once at API startup.

All heavy computation happened in the notebooks. This module's only job is to
read those results from disk and hold them in a single, typed container so the
API layer never touches the filesystem at request time.

The one exception is /simulate, which runs live LightGBM inference. For that,
we pre-compute `latest_ctx_df` here: one feature row per series at the most
recent available date, ready to have AveragePrice swapped out per request.
"""

from __future__ import annotations

import logging
import pathlib
import pickle
from dataclasses import dataclass
from typing import Any

import joblib
import pandas as pd

from src.config import settings

_log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Filesystem roots — resolved from Settings so Docker/env can override them.
# ---------------------------------------------------------------------------
_OUTPUTS = settings.outputs_dir
_PROCESSED = settings.processed_dir


# ---------------------------------------------------------------------------
# DataStore
# ---------------------------------------------------------------------------
@dataclass
class DataStore:
    """
    Single container for all artefacts the API serves.

    Every attribute is loaded once inside FastAPI's lifespan context manager
    and held in memory for the lifetime of the process.

    Attributes
    ----------
    forecast_df : DataFrame (1 032 × ~12)
        12-week point forecasts per series. Models: Ensemble_weighted, MSTL_ETS,
        MSTL_ARIMA, MSTL_Theta, NHITS, NBEATSx, DLinear, SeasonalNaive.
        Indexed by unique_id + ds.
    pi_df : DataFrame (86 × 7)
        Per-series conformal prediction-interval stats (lower_q, upper_q,
        resid_std, pi_width …). Applied to Ensemble_weighted forecasts.
    recommendations_df : DataFrame (86 × 9)
        Optimal price, revenue uplift, price elasticity per series.
    uncertainty_df : DataFrame (86 × 20)
        Conservative / balanced / aggressive strategy outputs plus risk metrics
        (rev_spread_pct, downside_risk_pct, uplift_sharpe, strategies_agree …).
    shap_drivers_df : DataFrame (258 × 7)
        Top-3 SHAP drivers per series (86 × 3 rows). Columns: unique_id,
        driver_rank, feature, shap_value, abs_shap_value, direction,
        feature_value.
    latest_ctx_df : DataFrame (86 × 44)
        Most-recent feature row per series from avocado_features.csv, with
        unique_id and region_encoded added. Used by /simulate for live
        inference: caller patches AveragePrice, everything else is fixed.
    model_bundle : dict
        Keys — 'model': trained LightGBM Booster, 'features': ordered list of
        26 feature names, 'target': 'log_total_volume'.
    series_meta : dict[str, dict]
        Keyed by unique_id → {'region': str, 'avocado_type': str}.
        Derived at load time so routes never have to parse unique_id strings.
    """

    forecast_df: pd.DataFrame
    pi_df: pd.DataFrame
    recommendations_df: pd.DataFrame
    uncertainty_df: pd.DataFrame
    shap_drivers_df: pd.DataFrame
    latest_ctx_df: pd.DataFrame
    model_bundle: dict
    series_meta: dict[str, dict]


# ---------------------------------------------------------------------------
# Private helpers
# ---------------------------------------------------------------------------

def _require(path: pathlib.Path) -> pathlib.Path:
    """Raise a clear FileNotFoundError if a required artefact is missing."""
    if not path.exists():
        raise FileNotFoundError(
            f"Required artefact not found: {path}\n"
            "Run the notebooks in order (01 → 06) to generate all outputs."
        )
    return path


def _load_csv(name: str) -> pd.DataFrame:
    return pd.read_csv(_require(_OUTPUTS / name))


def _build_latest_ctx(
    features_path: pathlib.Path,
    label_encoder: Any,
) -> pd.DataFrame:
    """
    Return one feature row per series at the most recent available date.

    Source file
    -----------
    data/processed/avocado_features.csv — generated by notebook 02.
    Expected shape: 14 190 rows × 42 columns (53 weeks × 43 regions × 2 types,
    minus rows dropped during feature construction).

    Required columns (subset used here):
      Date          datetime    Week ending date
      region        str         Market region name (e.g. "Albany")
      is_organic    int         1 = organic, 0 = conventional
      AveragePrice  float       Weekly average price (USD per avocado)
      Total Volume  float       Total weekly unit sales
      <26 model features>       See DataStore.model_bundle["features"] for the
                                complete ordered list required by LightGBM.

    Steps
    -----
    1. Load avocado_features.csv (14 190 rows, 42 columns).
    2. Construct unique_id as "{region}_{organic|conventional}" — matching the
       format used in every output artefact.
    3. Add region_encoded by re-applying the same LabelEncoder saved at
       training time. Using a different encoder would corrupt the model inputs.
    4. Keep only the last row per series (sorted by Date).
    """
    df = pd.read_csv(features_path, parse_dates=["Date"])

    df["unique_id"] = (
        df["region"] + "_"
        + df["is_organic"].map({1: "organic", 0: "conventional"})
    )

    # Must use the training-time encoder so integer codes match what the model saw.
    df["region_encoded"] = label_encoder.transform(df["region"])

    latest = (
        df.sort_values("Date")
        .groupby("unique_id", group_keys=False)
        .tail(1)
        .reset_index(drop=True)
    )
    return latest


def _build_series_meta(recommendations_df: pd.DataFrame) -> dict[str, dict]:
    """
    Build a lookup dict so routes never need to parse unique_id strings.

    unique_id format: "{region}_{organic|conventional}"
    is_organic column in recommendations_df: 1 or 0.
    """
    meta: dict[str, dict] = {}
    for _, row in recommendations_df.iterrows():
        uid: str = row["unique_id"]
        region = uid.rsplit("_", 1)[0]
        avocado_type = "organic" if int(row["is_organic"]) == 1 else "conventional"
        meta[uid] = {"region": region, "avocado_type": avocado_type}
    return meta


# ---------------------------------------------------------------------------
# Startup data integrity validation
# ---------------------------------------------------------------------------

def _validate(ds: DataStore) -> None:
    """
    Run lightweight sanity checks on the loaded DataStore.

    All checks are non-fatal: findings are logged as WARNING so the server
    starts even if data is partially degraded. A single INFO line is logged
    when all checks pass.

    Checks
    ------
    1. All 86 series have exactly 12 forecast weeks.
    2. No non-positive optimal prices in recommendations.
    3. Conformal PI lower_q < upper_q for every series.
    4. SHAP driver ranks 1, 2, 3 present for every series.
    5. LightGBM model smoke test: predict one row, verify positive output.
    """
    issues = 0

    # 1. Forecast completeness
    counts = ds.forecast_df.groupby("unique_id").size()
    bad = counts[counts != 12]
    if not bad.empty:
        _log.warning(
            "validation: %d series have != 12 forecast weeks: %s",
            len(bad), list(bad.index[:5]),
        )
        issues += len(bad)

    # 2. Price sanity
    bad_price = ds.recommendations_df[ds.recommendations_df["optimal_price"] <= 0]
    if not bad_price.empty:
        _log.warning(
            "validation: %d series have non-positive optimal_price: %s",
            len(bad_price), list(bad_price["unique_id"][:5]),
        )
        issues += len(bad_price)

    # 3. Prediction interval ordering
    bad_pi = ds.pi_df[ds.pi_df["lower_q"] >= ds.pi_df["upper_q"]]
    if not bad_pi.empty:
        _log.warning(
            "validation: %d series have lower_q >= upper_q in conformal PI",
            len(bad_pi),
        )
        issues += len(bad_pi)

    # 4. SHAP driver completeness
    rank_counts = ds.shap_drivers_df.groupby("unique_id")["driver_rank"].nunique()
    bad_ranks = rank_counts[rank_counts != 3]
    if not bad_ranks.empty:
        _log.warning(
            "validation: %d series have incomplete SHAP driver ranks: %s",
            len(bad_ranks), list(bad_ranks.index[:5]),
        )
        issues += len(bad_ranks)

    # 5. Model smoke test
    try:
        uid = next(iter(ds.series_meta))
        row = ds.latest_ctx_df[ds.latest_ctx_df["unique_id"] == uid].iloc[0]
        X = row[ds.model_bundle["features"]].to_frame().T.astype(float)
        pred = ds.model_bundle["model"].predict(X)
        if len(pred) != 1 or pred[0] <= 0:
            raise ValueError(f"unexpected prediction: {pred}")
    except Exception as exc:
        _log.warning("validation: model smoke test failed — %s", exc)
        issues += 1

    if issues == 0:
        _log.info("DataStore validation passed — all checks OK.")
    else:
        _log.warning(
            "DataStore validation completed with %d issue(s). "
            "Some recommendations may be unreliable.",
            issues,
        )


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

def load_datastore() -> DataStore:
    """
    Load every artefact from disk and return a fully populated DataStore.

    This function is called exactly once, inside FastAPI's lifespan context
    manager. After that, the DataStore is stored in app.state and injected
    into routes via a dependency function.

    Raises
    ------
    FileNotFoundError
        If any required file is missing. The message names the missing path
        and tells the user which notebook generates it.
    """
    label_encoder = joblib.load(_require(_OUTPUTS / "region_label_encoder.pkl"))

    # demand_model.pkl was saved with plain pickle (not joblib) in notebook 02.
    with open(_require(_OUTPUTS / "demand_model.pkl"), "rb") as fh:
        model_bundle = pickle.load(fh)

    latest_ctx_df = _build_latest_ctx(
        _require(_PROCESSED / "avocado_features.csv"),
        label_encoder,
    )

    recommendations_df = _load_csv("pricing_recommendations.csv")

    ds = DataStore(
        forecast_df=_load_csv("forecast_future.csv"),
        pi_df=_load_csv("conformal_pi_stats.csv"),
        recommendations_df=recommendations_df,
        uncertainty_df=_load_csv("uncertainty_pricing.csv"),
        shap_drivers_df=_load_csv("shap_top_drivers.csv"),
        latest_ctx_df=latest_ctx_df,
        model_bundle=model_bundle,
        series_meta=_build_series_meta(recommendations_df),
    )
    _validate(ds)
    return ds
